//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLineShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Sys_Registration_Info
    {
        public T_Sys_Registration_Info()
        {
            this.T_Tran_Detail_Transaction = new HashSet<T_Tran_Detail_Transaction>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> UserCreationDate { get; set; }
    
        public virtual ICollection<T_Tran_Detail_Transaction> T_Tran_Detail_Transaction { get; set; }
    }
}
