//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnLineShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Tran_Detail_Transaction
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int UnitId { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public int UserId { get; set; }
        public int TransactionId { get; set; }
    
        public virtual T_Sys_Item_Info T_Sys_Item_Info { get; set; }
        public virtual T_Sys_Registration_Info T_Sys_Registration_Info { get; set; }
        public virtual T_Sys_Unit_Info T_Sys_Unit_Info { get; set; }
        public virtual T_Tran_Master_Transaction T_Tran_Master_Transaction { get; set; }
    }
}
